Improve Dockerfile

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,4 +1,4 @@
-# This Dockerfile was inspired by https://github.com/vercel/next.js/tree/canary/examples/with-docker
+# This Dockerfile was heavily inspired by https://github.com/vercel/next.js/tree/canary/examples/with-docker
 
 FROM node:18-alpine AS base
 
@@ -6,14 +6,17 @@ FROM node:18-alpine AS base
 FROM base AS deps
 # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apk add --no-cache libc6-compat
-RUN npm install -g npm@latest
 WORKDIR /app
-COPY package.json package-lock.json ./
-RUN npm ci
 
-# If using yarn comment out above and use below instead
-# COPY package.json yarn.lock ./
-# RUN yarn install --frozen-lockfile
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm install -g npm@latest && npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
 
 # 2. Rebuild the source code only when needed
 FROM base AS builder
@@ -30,9 +33,12 @@ ENV NEXT_TELEMETRY_DISABLED 1
 ARG DOT_ENV_PRODUCTION_FILE=.env.production
 COPY ${DOT_ENV_PRODUCTION_FILE} .env.production
 
-RUN npm run build
-# If using yarn comment out above and use below instead
-# RUN yarn build
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # 3. Production image, copy all the files and run next
 FROM base AS runner
@@ -47,12 +53,14 @@ ENV NEXT_TELEMETRY_DISABLED 1
 RUN addgroup --system --gid 1001 nodejs
 RUN adduser --system --uid 1001 nextjs
 
-COPY --from=builder /app/next.config.js ./
 COPY --from=builder /app/public ./public
-COPY --from=builder /app/package.json ./package.json
+
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
 
 # Automatically leverage output traces to reduce image size
-# https://nextjs.org/docs/advanced-features/output-file-tracing
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
 COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
 COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
 
@@ -62,4 +70,4 @@ EXPOSE 3000
 
 ENV PORT 3000
 
-CMD ["node", "server.js"]
+CMD HOSTNAME="0.0.0.0" node server.js
